// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event } from "mygo-runtime";

// ---- Types ----

/** Filter selects which todos are listed. */
export type Filter = "all" | "active" | "done";

/** Stats summarizes the list. */
export interface Stats {
  total: number;
  active: number;
}

/** Todo is an item of the list. */
export interface Todo {
  id: number;
  title: string;
  done: boolean;
  createdAt: string;
}

// ---- Services ----

/**
 * Todos stores the list as JSON in the user data directory. Its exported
 * methods are callable from the frontend.
 */
export const Todos = {
  /** Add creates a todo. */
  add(title: string): Promise<Todo> {
    return call("Todos.Add", title);
  },
  /** ClearDone removes completed todos and returns how many were removed. */
  clearDone(): Promise<number> {
    return call("Todos.ClearDone");
  },
  /**
   * Export asks where to save the list and writes it as JSON. It returns the
   * chosen path, or "" when the dialog was canceled.
   */
  export(): Promise<string> {
    return call("Todos.Export");
  },
  /** List returns the todos matching filter, newest first. */
  list(filter: Filter): Promise<Todo[]> {
    return call("Todos.List", filter);
  },
  /** Remove deletes a todo. */
  remove(id: number): Promise<void> {
    return call("Todos.Remove", id);
  },
  /** Stats returns counters for the footer. */
  stats(): Promise<Stats> {
    return call("Todos.Stats");
  },
  /** Toggle marks a todo done or not done. */
  toggle(id: number): Promise<void> {
    return call("Todos.Toggle", id);
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** Changed is sent to every window whenever the list changes. */
  todosChanged: event<Stats>("todos:changed"),
} as const;
