// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event } from "mygo-runtime";

// ---- Services ----

/** Native is called from the page. */
export const Native = {
  /** Confirm asks a yes/no question. */
  confirm(question: string): Promise<boolean> {
    return call("Native.Confirm", question);
  },
  /** Copy puts text on the clipboard. */
  copy(text: string): Promise<void> {
    return call("Native.Copy", text);
  },
  /** Notify shows a desktop notification. */
  notify(title: string, body: string): Promise<void> {
    return call("Native.Notify", title, body);
  },
  /** OpenFiles lets the user pick files and returns their paths. */
  openFiles(): Promise<string[]> {
    return call("Native.OpenFiles");
  },
  /** Paste reads text from the clipboard. */
  paste(): Promise<string> {
    return call("Native.Paste");
  },
  /** SetDark switches between the light and dark appearance. */
  setDark(dark: boolean): Promise<void> {
    return call("Native.SetDark", dark);
  },
  /** ShowContextMenu pops up a native context menu at the mouse position. */
  showContextMenu(): Promise<void> {
    return call("Native.ShowContextMenu");
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** Log is sent to the page for anything worth showing. */
  log: event<string>("log"),
} as const;
