package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// The frontend is embedded into production builds without touching the
// project: `go build -overlay` adds a generated file to the app's package
// that embeds the frontendDist files, which the overlay maps into a
// directory of the package, and hands them to mygo.SetFrontend.
const (
	frontendGenFile = "mygo_frontend_gen.go"
	frontendGenDir  = "mygo_frontend"
)

const frontendGenSource = `// Code generated by mygo build. DO NOT EDIT.

package main

import (
	"embed"
	"io/fs"

	"github.com/egoist/mygo"
)

//go:embed all:` + frontendGenDir + `
var mygoFrontendFiles embed.FS

func init() {
	files, _ := fs.Sub(mygoFrontendFiles, "` + frontendGenDir + `")
	mygo.SetFrontend(files)
}
`

// frontendOverlay writes, in work, the overlay that embeds FrontendDist
// and returns its path, or "" when the app has no frontend to embed.
func frontendOverlay(c *Config, work string) (string, error) {
	if c.FrontendDist == "" {
		return "", nil
	}
	dist := c.path(c.FrontendDist)
	pkg, err := packageDir(c)
	if err != nil {
		return "", err
	}
	for _, name := range []string{frontendGenFile, frontendGenDir} {
		if _, err := os.Lstat(filepath.Join(pkg, name)); err == nil {
			return "", fmt.Errorf("%s is in the way of embedding the frontend; rename it", filepath.Join(pkg, name))
		}
	}
	replace := map[string]string{}
	err = filepath.WalkDir(dist, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !d.Type().IsRegular() {
			return nil
		}
		rel, err := filepath.Rel(dist, path)
		if err != nil {
			return err
		}
		replace[filepath.Join(pkg, frontendGenDir, rel)] = path
		return nil
	})
	if os.IsNotExist(err) {
		return "", fmt.Errorf("frontendDist %s does not exist; set buildCommand in mygo.json to build it", c.FrontendDist)
	}
	if err != nil {
		return "", err
	}
	if len(replace) == 0 {
		return "", fmt.Errorf("frontendDist %s is empty", c.FrontendDist)
	}
	gen := filepath.Join(work, frontendGenFile)
	if err := os.WriteFile(gen, []byte(frontendGenSource), 0o644); err != nil {
		return "", err
	}
	replace[filepath.Join(pkg, frontendGenFile)] = gen
	data, err := json.Marshal(struct{ Replace map[string]string }{replace})
	if err != nil {
		return "", err
	}
	overlay := filepath.Join(work, "overlay.json")
	return overlay, os.WriteFile(overlay, data, 0o644)
}

// packageDir returns the directory of the app's main package.
func packageDir(c *Config) (string, error) {
	var out bytes.Buffer
	cmd := goCommand(c.root, nil, "list", "-f", "{{.Dir}}", c.Main)
	cmd.Stdout = &out
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("go list %s: %w", c.Main, err)
	}
	return strings.TrimSpace(out.String()), nil
}
